USE MASTER
GO
-- Kiểm tra xem cơ sở dữ liệu 'SFCM' đã tồn tại chưa
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'SFCM')
BEGIN
    -- Nếu tồn tại, thì xóa cơ sở dữ liệu 'SFCM'
    DROP DATABASE SFCM
END
-- Tạo mới cơ sở dữ liệu 'SFCM'
GO
CREATE DATABASE SFCM

-- Sử dụng cơ sở dữ liệu 'SFCM' để tạo các bảng
GO
USE SFCM
GO
/****** Object:  Table [dbo].[BS_BLOCK]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_BLOCK](
	[ROWGUID] [uniqueidentifier] NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NOT NULL,
	[BLOCK] [nvarchar](5) NOT NULL,
	[TIER_COUNT] [int] NULL,
	[SLOT_COUNT] [int] NULL,
	[STATUS] [int] NULL,
	[CREATE_BY] [nvarchar](500) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_CUSTOMER]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_CUSTOMER](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[CUSTOMER_TYPE_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_NAME] [nvarchar](500) NOT NULL,
	[ACC_TYPE] [nvarchar](3) NOT NULL,
	[ADDRESS] [nvarchar](max) NULL,
	[TAX_CODE] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](200) NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK__BS_CUSTO__3214EC27F521F830] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_CUSTOMER_TYPE]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_CUSTOMER_TYPE](
	[ROWGUID] [uniqueidentifier] NULL,
	[CUSTOMER_TYPE_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_TYPE_NAME] [nvarchar](500) NOT NULL,
	[CREATE_BY] [nvarchar](500) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_EQUIPMENTS]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_EQUIPMENTS](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[EQU_TYPE] [nvarchar](10) NOT NULL,
	[EQU_CODE] [nvarchar](10) NOT NULL,
	[EQU_CODE_NAME] [nvarchar](50) NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NULL,
	[BLOCK] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_EQUIPMENTS_TYPE]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_EQUIPMENTS_TYPE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[EQU_TYPE] [nvarchar](10) NOT NULL,
	[EQU_TYPE_NAME] [nvarchar](50) NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_GATE]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_GATE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[GATE_CODE] [nvarchar](50) NOT NULL,
	[GATE_NAME] [nvarchar](500) NOT NULL,
	[IS_IN_OUT] [char](1) NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_ITEM_TYPE]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_ITEM_TYPE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[ITEM_TYPE_NAME] [nvarchar](500) NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_METHOD]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_METHOD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[METHOD_NAME] [nvarchar](500) NOT NULL,
	[IS_IN_OUT] [char](1) NOT NULL,
	[CLASS_CODE] [int] NOT NULL,
	[IS_SERVICE] [int] NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK__BS_METHO__3214EC27738454F4] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_ROMOOC]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_ROMOOC](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[REMOOC_NO] [nvarchar](50) NULL,
	[REMOOC_WEIGHT] [numeric](18, 2) NULL,
	[REMOOC_WEIGHT_REGIS] [numeric](18, 2) NULL,
	[REMOOC_DATE_EXP] [datetime] NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_TRUCK]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_TRUCK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[TRUCK_NO] [nvarchar](50) NULL,
	[WEIGHT_REGIS] [numeric](18, 2) NULL,
	[WEIGHT_REGIS_ALLOW] [numeric](18, 2) NULL,
	[TRUCK_DATE_EXP] [datetime] NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_UNIT]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_UNIT](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[UNIT_CODE] [nvarchar](50) NOT NULL,
	[UNIT_NAME] [nvarchar](500) NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_WAREHOUSE]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_WAREHOUSE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NOT NULL,
	[WAREHOUSE_NAME] [nvarchar](500) NOT NULL,
	[ACREAGE] [numeric](18, 3) NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIG_ATTACH_SERVICE]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIG_ATTACH_SERVICE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NULL,
	[CUSTOMER_CODE] [nvarchar](50) NULL,
	[METHOD_CODE] [nvarchar](50) NULL,
	[ATTACH_SERVICE_CODE] [nvarchar](50) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONFIG_ATTACH_SERVICE] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIG_FREE_DAYS]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIG_FREE_DAYS](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[NAME] [nvarchar](max) NULL,
	[CUSTOMER_CODE] [nvarchar](50) NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[APPLY_DATE] [datetime] NOT NULL,
	[EXPIRE_DATE] [datetime] NOT NULL,
	[CLASS_CODE] [nvarchar](1) NOT NULL,
	[START_TIME] [nvarchar](100) NOT NULL,
	[FREE_DAYS] [numeric](12, 2) NOT NULL,
	[ACC_TYPE] [nvarchar](3) NOT NULL,
	[CREATE_BY] [nvarchar](20) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](20) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK__CONFIG_F__3214EC27EE55C904] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_CNTR_MNF_LD]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_CNTR_MNF_LD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[CLASS_CODE] [int] NOT NULL,
	[TRANSPORTIDENTITY] [nvarchar](200) NOT NULL,
	[NUMBEROFJOURNEY] [varchar](20) NOT NULL,
	[ARRIVALDEPARTURE] [datetime] NOT NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[BOOKING_NO] [varchar](50) NULL,
	[SEALNO] [nvarchar](35) NULL,
	[CNTRNO] [varchar](11) NOT NULL,
	[CNTRSZTP] [varchar](5) NOT NULL,
	[STATUSOFGOOD] [bit] NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK__DT_CNTR___3214EC277334079B] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_CNTR_STOCK]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_CNTR_STOCK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[CLASS_CODE] [int] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[CNTRNO] [varchar](11) NOT NULL,
	[CNTRSZTP] [varchar](5) NOT NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[BOOKING_NO] [varchar](50) NULL,
	[GET_IN] [datetime] NULL,
	[GET_OUT] [datetime] NULL,
	[GETOUT_TRUCK] [varchar](30) NULL,
	[JOBMODE_IN] [varchar](50) NULL,
	[JOBMODE_OUT] [varchar](50) NULL,
	[NATUREOFTRANSPORT] [varchar](10) NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
	[SEALNO] [varchar](200) NULL,
	[CONTAINERLOCATION] [varchar](100) NULL,
	[CARGO_WEIGHT] [decimal](10, 3) NULL,
	[REMARK] [nvarchar](max) NULL,
	[CHK_FE] [bit] NULL,
	[CHK_LCL] [bit] NULL,
	[ISLOCALFOREIGN] [char](1) NULL,
	[TLHQ] [bit] NULL,
	[ID_TOS] [uniqueidentifier] NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_CNTR_STOCK] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_ORDER]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_ORDER](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[CLASS_CODE] [int] NOT NULL,
	[ORDER_NO] [nvarchar](50) NOT NULL,
	[PIN_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_CODE] [nvarchar](50) NULL,
	[ACC_TYPE] [nvarchar](3) NULL,
	[ACC_CD] [nvarchar](10) NULL,
	[DELIVERY_ORDER] [nvarchar](100) NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[BOOKING_NO] [varchar](50) NULL,
	[CNTRNO] [varchar](11) NULL,
	[CNTRSZTP] [varchar](5) NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[ITEM_TYPE_CODE_CNTR] [nvarchar](50) NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[ISSUE_DATE] [datetime] NOT NULL,
	[EXP_DATE] [datetime] NOT NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[BOOKING_FWD] [nvarchar](200) NULL,
	[CARGO_PIECE] [int] NULL,
	[UNIT_CODE] [nvarchar](50) NULL,
	[CARGO_WEIGHT] [decimal](10, 3) NULL,
	[CBM] [decimal](10, 3) NULL,
	[RT] [decimal](10, 3) NULL,
	[LOT_NO] [nvarchar](10) NULL,
	[NOTE] [nvarchar](max) NULL,
	[DRAFT_NO] [nvarchar](20) NULL,
	[INV_NO] [nvarchar](20) NULL,
	[GATE_CHK] [bit] NOT NULL,
	[QUANTITY_CHK] [bit] NOT NULL,
	[OWNER_REPRESENT] [nvarchar](500) NULL,
	[OWNER_PHONE] [nvarchar](500) NULL,
	[OWNER] [nvarchar](500) NULL,
	[PAYMENT_CHK] [bit] NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
 CONSTRAINT [PK__DT_ORDER__3214EC2756BD8963] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_PACKAGE_MNF_LD]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_PACKAGE_MNF_LD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[TRANSPORTIDENTITY] [nvarchar](200) NOT NULL,
	[NUMBEROFJOURNEY] [varchar](20) NOT NULL,
	[ARRIVALDEPARTURE] [datetime] NOT NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[BOOKING_NO] [varchar](50) NULL,
	[CNTRNO] [varchar](11) NULL,
	[CNTRSZTP] [varchar](5) NULL,
	[ITEM_TYPE_CODE_CNTR] [nvarchar](50) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[BOOKING_FWD] [nvarchar](200) NULL,
	[LOT_NO] [nvarchar](10) NULL,
	[SHIPMARKS] [nvarchar](max) NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
	[CARGO_PIECE] [int] NOT NULL,
	[UNIT_CODE] [nvarchar](50) NOT NULL,
	[CARGO_WEIGHT] [decimal](10, 3) NOT NULL,
	[CBM] [decimal](10, 3) NOT NULL,
	[DECLARE_NO] [varchar](max) NULL,
	[NOTE] [nvarchar](200) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[CLASS_CODE] [int] NOT NULL,
	[CUSTOMER_NAME] [nvarchar](500) NOT NULL,
	[CONSIGNEE] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK__DT_PACKA__3214EC27CE0DCB22] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_PACKAGE_STOCK]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_PACKAGE_STOCK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NULL,
	[CLASS_CODE] [int] NULL,
	[ORDER_NO] [nvarchar](50) NULL,
	[PIN_CODE] [nvarchar](50) NULL,
	[CUSTOMER_TYPE_CODE] [nvarchar](50) NULL,
	[CUSTOMER_CODE] [nvarchar](50) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[BOOKING_FWD] [varchar](50) NULL,
	[CNTRNO] [varchar](11) NULL,
	[LOT_NO] [nvarchar](10) NULL,
	[STATUS] [char](1) NULL,
	[TIME_IN] [datetime] NULL,
	[TIME_OUT] [datetime] NULL,
	[CARGO_PIECE] [int] NULL,
	[UNIT_CODE] [nvarchar](50) NULL,
	[CARGO_WEIGHT] [decimal](10, 3) NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NULL,
	[CBM] [decimal](10, 3) NULL,
	[TLHQ] [bit] NULL,
	[GETIN_HQ] [bit] NULL,
	[METHOD_IN] [nvarchar](50) NULL,
	[GETOUT_HQ] [bit] NULL,
	[METHOD_OUT] [nvarchar](50) NULL,
	[TKHN_NO] [varchar](100) NULL,
	[TKHX_NO] [varchar](100) NULL,
	[CUSTOMER_CAS] [varchar](200) NULL,
	[NOTE] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
 CONSTRAINT [PK__DT_STOCK__3214EC27C5214B7B] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_PALLET_STOCK]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_PALLET_STOCK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[IDREF_STOCK] [bigint] NOT NULL,
	[HOUSE_BILL] [varchar](50) NULL,
	[BOOKING_FWD] [varchar](50) NULL,
	[PALLET_NO] [nvarchar](100) NULL,
	[CARGO_PIECE] [int] NULL,
	[UNIT_CODE] [nvarchar](50) NULL,
	[WAREHOUSE_CODE] [varchar](50) NULL,
	[BLOCK] [nvarchar](5) NULL,
	[SLOT] [int] NULL,
	[TIER] [int] NULL,
	[STATUS] [char](1) NULL,
	[NOTE] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK__DT_PALLE__3214EC274EBFF72C] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_VESSEL_VISIT]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_VESSEL_VISIT](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[VESSEL_NAME] [nvarchar](200) NOT NULL,
	[INBOUND_VOYAGE] [varchar](20) NULL,
	[OUTBOUND_VOYAGE] [varchar](20) NULL,
	[ETA] [datetime] NULL,
	[ETD] [datetime] NULL,
	[CallSign] [varchar](50) NULL,
	[IMO] [varchar](30) NULL,
	[TOS_SHIPKEY] [nvarchar](50) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK__DT_VESSE__3214EC279EC89011] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_DFT]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_DFT](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[DRAFT_INV_NO] [nvarchar](20) NOT NULL,
	[INV_NO] [nvarchar](20) NULL,
	[DRAFT_INV_DATE] [datetime] NULL,
	[REF_NO] [nvarchar](300) NULL,
	[PAYER_TYPE] [nvarchar](3) NULL,
	[PAYER] [nvarchar](20) NULL,
	[AMOUNT] [numeric](12, 2) NULL,
	[VAT] [numeric](12, 2) NULL,
	[DIS_AMT] [numeric](12, 2) NULL,
	[REMARK] [nvarchar](100) NULL,
	[PAYMENT_STATUS] [nvarchar](1) NULL,
	[CURRENCYID] [nvarchar](3) NULL,
	[RATE] [numeric](14, 2) NULL,
	[INV_TYPE] [nvarchar](3) NULL,
	[TPLT_NM] [nvarchar](200) NULL,
	[IS_MANUAL_INV] [nvarchar](1) NULL,
	[TAMOUNT] [numeric](12, 2) NULL,
	[CREATE_BY] [nvarchar](50) NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](50) NULL,
 CONSTRAINT [PKINV_DFT3214EC276DEF1240] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_DFT_DTL]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_DFT_DTL](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[DRAFT_INV_NO] [nvarchar](20) NOT NULL,
	[SEQ] [int] NOT NULL,
	[TRF_CODE] [nvarchar](12) NULL,
	[IX_CD] [nvarchar](1) NULL,
	[CARGO_TYPE] [nvarchar](2) NULL,
	[SZ] [nvarchar](4) NULL,
	[QTY] [numeric](12, 2) NULL,
	[UNIT_RATE] [numeric](15, 5) NULL,
	[AMOUNT] [numeric](12, 2) NULL,
	[DIS_RATE] [numeric](14, 2) NULL,
	[DIS_AMT] [numeric](12, 2) NULL,
	[VAT_RATE] [numeric](5, 2) NULL,
	[VAT] [numeric](12, 2) NULL,
	[TAMOUNT] [numeric](12, 2) NULL,
	[JOB_TYPE] [nvarchar](4) NULL,
	[TRF_DESC] [nvarchar](500) NULL,
	[INV_UNIT] [nvarchar](3) NULL,
	[VAT_CHK] [bit] NULL,
	[REMARK] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](50) NULL,
 CONSTRAINT [PK__INV_DFT___3214EC27EB0BD552] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_VAT]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_VAT](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[INV_NO] [nvarchar](20) NOT NULL,
	[INV_DATE] [datetime] NULL,
	[REF_NO] [nvarchar](200) NULL,
	[PAYER_TYPE] [nvarchar](3) NULL,
	[PAYER] [nvarchar](20) NULL,
	[AMOUNT] [numeric](12, 2) NULL,
	[VAT] [numeric](12, 2) NULL,
	[DIS_AMT] [numeric](12, 2) NULL,
	[REMARK] [nvarchar](100) NULL,
	[PAYMENT_STATUS] [nvarchar](1) NULL,
	[CURRENCYID] [nvarchar](3) NULL,
	[RATE] [numeric](14, 2) NULL,
	[INV_TYPE] [nvarchar](3) NULL,
	[TPLT_NM] [nvarchar](200) NULL,
	[LOCAL_INV] [nvarchar](12) NULL,
	[TAMOUNT] [numeric](12, 2) NULL,
	[ACC_CD] [nvarchar](10) NULL,
	[IS_POSTED] [nvarchar](1) NULL,
	[INV_PREFIX] [nvarchar](20) NULL,
	[INV_NO_PRE] [nvarchar](20) NULL,
	[CANCEL_DATE] [datetime] NULL,
	[CANCLE_REMARK] [nvarchar](200) NULL,
	[CANCLE_BY] [nvarchar](25) NULL,
	[ISDFT_TO_INV] [varchar](1) NULL,
	[PIN_CODE] [nvarchar](20) NULL,
	[CREATE_BY] [nvarchar](100) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_BY] [nvarchar](100) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[VOYAGEKEY] [nvarchar](50) NULL,
 CONSTRAINT [PK__INV_VAT__3214EC27F2A2224B] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_GATE]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_GATE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[CLASS_CODE] [int] NOT NULL,
	[METHOD_CODE] [nvarchar](50) NULL,
	[ORDER_NO] [nvarchar](50) NOT NULL,
	[PIN_CODE] [nvarchar](50) NULL,
	[GATE_CODE] [nvarchar](50) NOT NULL,
	[IS_IN_OUT] [char](1) NOT NULL,
	[DRIVER] [nvarchar](500) NULL,
	[TEL] [nvarchar](20) NULL,
	[TRUCK_NO] [nvarchar](50) NULL,
	[REMOOC_NO] [nvarchar](50) NULL,
	[WEIGHT_REGIS] [numeric](18, 2) NULL,
	[WEIGHT_REGIS_ALLOW] [numeric](18, 2) NULL,
	[REMOOC_WEIGHT] [numeric](18, 2) NULL,
	[REMOOC_WEIGHT_REGIS] [numeric](18, 2) NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[BOOKING_NO] [varchar](50) NULL,
	[CNTRNO] [varchar](11) NULL,
	[CNTRSZTP] [nvarchar](5) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[BOOKING_FWD] [nvarchar](200) NULL,
	[CARGO_PIECE] [int] NULL,
	[UNIT_CODE] [nvarchar](50) NULL,
	[CARGO_WEIGHT] [decimal](10, 3) NULL,
	[CBM] [decimal](10, 3) NULL,
	[NOTE] [nvarchar](max) NULL,
	[CUSTOMER_CODE] [nvarchar](50) NULL,
	[TIME_IN] [datetime] NULL,
	[TIME_OUT] [datetime] NULL,
	[IS_SUCCESS_IN] [bit] NULL,
	[IS_SUCCESS_OUT] [bit] NULL,
	[QUANTITY_CHK] [bit] NULL,
	[VGM] [bit] NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK__JOB_GATE__3214EC2790EB5E07] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_QUANTITY_CHECK]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_QUANTITY_CHECK](
	[ROWGUID] [uniqueidentifier] NULL,
	[VOYAGEKEY] [nvarchar](50) NULL,
	[WAREHOUSE_CODE] [varchar](50) NULL,
	[CLASS_CODE] [int] NULL,
	[METHOD_CODE] [nvarchar](50) NULL,
	[TRUCK_NO] [nvarchar](50) NULL,
	[CNTRNO] [varchar](11) NULL,
	[ORDER_NO] [nvarchar](50) NULL,
	[PIN_CODE] [nvarchar](50) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[BOOKING_FWD] [nvarchar](200) NULL,
	[BOOKING_NO] [nvarchar](200) NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NULL,
	[ESTIMATED_CARGO_PIECE] [int] NULL,
	[ACTUAL_CARGO_PIECE] [int] NULL,
	[ACTUAL_UNIT] [nvarchar](50) NULL,
	[ACTUAL_CARGO_WEIGHT] [decimal](10, 3) NULL,
	[SEQ] [int] NULL,
	[PALLET_NO] [nvarchar](100) NULL,
	[START_DATE] [datetime] NULL,
	[FINISH_DATE] [datetime] NULL,
	[IS_FINAL] [bit] NULL,
	[JOB_STATUS] [char](1) NULL,
	[NOTE] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NULL,
	[UPDATE_DATE] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_STOCK]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_STOCK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NULL,
	[WAREHOUSE_CODE] [varchar](50) NULL,
	[CLASS_CODE] [int] NULL,
	[JOB_TYPE] [nvarchar](10) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[BOOKING_FWD] [nvarchar](200) NULL,
	[ORDER_NO] [nvarchar](50) NULL,
	[PIN_CODE] [nvarchar](50) NULL,
	[PALLET_NO] [nvarchar](100) NULL,
	[SEQ] [int] NULL,
	[ACTUAL_CARGO_PIECE] [int] NULL,
	[ACTUAL_UNIT] [nvarchar](50) NULL,
	[ACTUAL_CARGO_WEIGHT] [decimal](10, 3) NULL,
	[BLOCK] [nvarchar](5) NULL,
	[SLOT] [int] NULL,
	[TIER] [int] NULL,
	[JOB_STATUS] [char](1) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK__JOB_STOC__3214EC2767B739E6] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECEIPTS]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECEIPTS](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NULL,
	[WAREHOUSE_CODE] [varchar](50) NULL,
	[ORDER_NO] [nvarchar](50) NULL,
	[CLASS_CODE] [int] NULL,
	[JOB_TYPE] [nvarchar](10) NULL,
	[RECEIPT_NO] [nvarchar](20) NULL,
	[RECEIPT_DATE] [datetime] NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[BOOKING_NO] [varchar](50) NULL,
	[CNTRNO] [varchar](11) NULL,
	[CNTRSZTP] [varchar](5) NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NULL,
	[ITEM_TYPE_CODE_CNTR] [nvarchar](50) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[BOOKING_FWD] [nvarchar](200) NULL,
	[ACTUAL_CARGO_PIECE] [int] NULL,
	[UNIT_CODE] [nvarchar](50) NULL,
	[CARGO_WEIGHT] [decimal](10, 3) NULL,
	[CBM] [decimal](10, 3) NULL,
	[NOTE] [nvarchar](max) NULL,
	[VESSEL_NAME] [nvarchar](200) NULL,
	[OWNER] [nvarchar](500) NULL,
	[ADDRESS] [nvarchar](max) NULL,
	[OWNER_PHONE] [nvarchar](200) NULL,
	[PAYER] [nvarchar](500) NULL,
	[VESSEL_BOUND] [varchar](20) NULL,
	[TRUCK_NO] [nvarchar](50) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK__RECEIPTS__3214EC2777AFF5B2] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_MENU]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_MENU](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[PARENT_CODE] [nvarchar](255) NULL,
	[MENU_CODE] [nvarchar](100) NOT NULL,
	[MENU_NAME] [nvarchar](max) NOT NULL,
	[MENU_ICON] [nvarchar](255) NULL,
	[IS_VISIBLE] [bit] NOT NULL,
	[ORDER_BY] [bigint] NOT NULL,
	[VIEW_PAGE] [nvarchar](100) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_PERMISSION]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_PERMISSION](
	[ROWGUID] [uniqueidentifier] NULL,
	[ROLE_CODE] [nvarchar](100) NOT NULL,
	[MENU_CODE] [nvarchar](500) NOT NULL,
	[IS_VIEW] [bit] NULL,
	[IS_ADD_NEW] [bit] NULL,
	[IS_MODIFY] [bit] NULL,
	[IS_DELETE] [bit] NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_ROLE]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_ROLE](
	[ROWGUID] [uniqueidentifier] NULL,
	[ROLE_CODE] [nvarchar](50) NOT NULL,
	[ROLE_NAME] [nvarchar](500) NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_USER]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_USER](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[USER_NAME] [nvarchar](max) NOT NULL,
	[PASSWORD] [nvarchar](100) NULL,
	[ROLE_CODE] [nvarchar](100) NOT NULL,
	[FULLNAME] [nvarchar](50) NULL,
	[BIRTHDAY] [datetime] NULL,
	[ADDRESS] [nvarchar](500) NULL,
	[TELEPHONE] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](max) NULL,
	[IS_ACTIVE] [bit] NULL,
	[REMARK] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK__SA_USERS__3214EC27E75F64CC] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_CODES]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_CODES](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[TRF_CODE] [nvarchar](12) NOT NULL,
	[TRF_DESC] [nvarchar](150) NOT NULL,
	[INV_UNIT] [nvarchar](3) NOT NULL,
	[VAT_CHK] [bit] NOT NULL,
	[REVENUE_ACC] [nvarchar](20) NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK__TRF_CODE__3214EC27C2E329E5] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_STD]    Script Date: 5/15/2024 10:58:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_STD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[TRF_CODE] [nvarchar](12) NOT NULL,
	[TRF_DESC] [nvarchar](150) NOT NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[CURRENCY_CODE] [nvarchar](3) NOT NULL,
	[AMT_MIN20] [numeric](12, 2) NULL,
	[AMT_MIN40] [numeric](12, 2) NULL,
	[AMT_MIN45] [numeric](12, 2) NULL,
	[AMT_RT] [numeric](12, 2) NULL,
	[AMT_NON] [numeric](12, 2) NULL,
	[VAT] [numeric](5, 2) NULL,
	[INCLUDE_VAT] [int] NULL,
	[FROM_DATE] [nvarchar](30) NOT NULL,
	[TO_DATE] [nvarchar](30) NOT NULL,
	[TRF_NAME] [nvarchar](100) NOT NULL,
	[TRF_TEMP] [nvarchar](200) NOT NULL,
	[CREATE_BY] [nvarchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[CLASS_CODE] [nvarchar](1) NOT NULL,
 CONSTRAINT [PK__TRF_STD__3214EC27E13AE5C8] PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BS_BLOCK] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_BLOCK] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  CONSTRAINT [DF__BS_CUSTOM__ROWGU__6C190EBB]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  CONSTRAINT [DF__BS_CUSTOM__IS_AC__6D0D32F4]  DEFAULT ((0)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  CONSTRAINT [DF__BS_CUSTOM__CREAT__6E01572D]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER_TYPE] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_CUSTOMER_TYPE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS_TYPE] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS_TYPE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_GATE] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_GATE] ADD  DEFAULT ('I') FOR [IS_IN_OUT]
GO
ALTER TABLE [dbo].[BS_GATE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_ITEM_TYPE] ADD  CONSTRAINT [DF_BS_ITEM_TYPE_ROWGUID]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_METHOD] ADD  CONSTRAINT [DF__BS_METHOD__ROWGU__72910220]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_METHOD] ADD  CONSTRAINT [DF_BS_METHOD_IS_SERVICE]  DEFAULT ((0)) FOR [IS_SERVICE]
GO
ALTER TABLE [dbo].[BS_ROMOOC] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_TRUCK] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_UNIT] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_UNIT] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_WAREHOUSE] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_WAREHOUSE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[CONFIG_ATTACH_SERVICE] ADD  CONSTRAINT [DF__SYS_CONFI__Rowgu__01D345B0]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[CONFIG_ATTACH_SERVICE] ADD  CONSTRAINT [DF__SYS_CONFI__Creat__02C769E9]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[CONFIG_FREE_DAYS] ADD  CONSTRAINT [DF__CONFIG_FR__ROWGU__10AB74EC]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  CONSTRAINT [DF__DT_CNTR_M__ROWGU__47A6A41B]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  CONSTRAINT [DF__DT_CNTR_M__CREAT__489AC854]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_CNTR_STOCK] ADD  CONSTRAINT [DF_DT_CNTR_STOCK_ROWGUID]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_CNTR_STOCK] ADD  CONSTRAINT [DF__DT_CNTR_S__CntrS__7908F585]  DEFAULT ('NA') FOR [CNTRSZTP]
GO
ALTER TABLE [dbo].[DT_CNTR_STOCK] ADD  CONSTRAINT [DF__DT_CNTR_S__CHK_F__79FD19BE]  DEFAULT ((0)) FOR [CHK_FE]
GO
ALTER TABLE [dbo].[DT_CNTR_STOCK] ADD  CONSTRAINT [DF__DT_CNTR_S__CHK_L__7AF13DF7]  DEFAULT ((0)) FOR [CHK_LCL]
GO
ALTER TABLE [dbo].[DT_CNTR_STOCK] ADD  CONSTRAINT [DF_DT_CNTR_STOCK_TLHQ]  DEFAULT ((0)) FOR [TLHQ]
GO
ALTER TABLE [dbo].[DT_ORDER] ADD  CONSTRAINT [DF__DT_ORDER__ROWGUI__66603565]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_ORDER] ADD  CONSTRAINT [DF_DT_ORDER_GATE_CHK]  DEFAULT ((0)) FOR [GATE_CHK]
GO
ALTER TABLE [dbo].[DT_ORDER] ADD  CONSTRAINT [DF_DT_ORDER_QUANTITY_CHK]  DEFAULT ((0)) FOR [QUANTITY_CHK]
GO
ALTER TABLE [dbo].[DT_ORDER] ADD  CONSTRAINT [DF_DT_ORDER_PAYMENT_CHK]  DEFAULT ((0)) FOR [PAYMENT_CHK]
GO
ALTER TABLE [dbo].[DT_ORDER] ADD  CONSTRAINT [DF__DT_ORDER__CREATE__693CA210]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] ADD  CONSTRAINT [DF__DT_PACKAG__ROWGU__214BF109]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] ADD  CONSTRAINT [DF__DT_STOCK__ROWGUI__74AE54BC]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] ADD  CONSTRAINT [DF_DT_PACKAGE_STOCK_TLHQ]  DEFAULT ((0)) FOR [TLHQ]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] ADD  CONSTRAINT [DF_DT_PACKAGE_STOCK_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] ADD  CONSTRAINT [DF__DT_PALLET__ROWGU__056ECC6A]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] ADD  CONSTRAINT [DF__DT_PALLET__CREAT__0662F0A3]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_VESSEL_VISIT] ADD  CONSTRAINT [DF__DT_VESSEL__ROWGU__43D61337]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_VESSEL_VISIT] ADD  CONSTRAINT [DF__DT_VESSEL__CREAT__44CA3770]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[INV_DFT] ADD  CONSTRAINT [DFINV_DFTROWGUID__15A53433]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[INV_DFT_DTL] ADD  CONSTRAINT [DF__INV_DFT_D__ROWGU__1881A0DE]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[INV_VAT] ADD  CONSTRAINT [DF__INV_VAT__ROWGUID__2116E6DF]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF__JOB_GATE__ROWGUI__7E37BEF6]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF_JOB_GATE_WEIGHT_REGIS]  DEFAULT ((0)) FOR [WEIGHT_REGIS]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF_JOB_GATE_WEIGHT_REGIS_ALLOW]  DEFAULT ((0)) FOR [WEIGHT_REGIS_ALLOW]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF__JOB_GATE__IS_LOC__7F2BE32F]  DEFAULT ((0)) FOR [REMOOC_WEIGHT]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF_JOB_GATE_REMOOC_WEIGHT_REGIS]  DEFAULT ((0)) FOR [REMOOC_WEIGHT_REGIS]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF__JOB_GATE__IS_SUC__00200768]  DEFAULT ((0)) FOR [CNTRSZTP]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF_JOB_GATE_IS_SUCCESS_IN]  DEFAULT ((0)) FOR [IS_SUCCESS_IN]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF_JOB_GATE_IS_SUCCESS_OUT]  DEFAULT ((0)) FOR [IS_SUCCESS_OUT]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF_JOB_GATE_QUANTITY_CHK]  DEFAULT ((0)) FOR [QUANTITY_CHK]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF_JOB_GATE_VGM]  DEFAULT ((0)) FOR [VGM]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  CONSTRAINT [DF__JOB_GATE__CREATE__01142BA1]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] ADD  CONSTRAINT [DF__JOB_QUANT__ROWGU__03F0984C]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] ADD  CONSTRAINT [DF__JOB_QUANT__CHECK__04E4BC85]  DEFAULT ((0)) FOR [IS_FINAL]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] ADD  CONSTRAINT [DF__JOB_QUANT__CREAT__05D8E0BE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[JOB_STOCK] ADD  CONSTRAINT [DF__JOB_STOCK__ROWGU__6F4A8121]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[JOB_STOCK] ADD  CONSTRAINT [DEFAULT_JOB_STOCK_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[JOB_STOCK] ADD  CONSTRAINT [DEFAULT_JOB_STOCK_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[RECEIPTS] ADD  CONSTRAINT [DF__RECEIPTS__ROWGUI__6B44E613]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[RECEIPTS] ADD  CONSTRAINT [DF__RECEIPTS__RECEIP__6C390A4C]  DEFAULT (getdate()) FOR [RECEIPT_DATE]
GO
ALTER TABLE [dbo].[RECEIPTS] ADD  CONSTRAINT [DEFAULT_RECEIPTS_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[RECEIPTS] ADD  CONSTRAINT [DEFAULT_RECEIPTS_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DF__SA_MENU__ROWGUID__14270015]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DF__SA_MENU__IS_VISI__151B244E]  DEFAULT ((1)) FOR [IS_VISIBLE]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DF__SA_MENU__ORDER_B__160F4887]  DEFAULT ((0)) FOR [ORDER_BY]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DEFAULT_SA_MENU_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  CONSTRAINT [DEFAULT_SA_MENU_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  DEFAULT ((0)) FOR [IS_VIEW]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  DEFAULT ((0)) FOR [IS_ADD_NEW]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  DEFAULT ((0)) FOR [IS_MODIFY]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  DEFAULT ((0)) FOR [IS_DELETE]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  CONSTRAINT [DEFAULT_SA_PERMISSION_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  CONSTRAINT [DF__SA_USERGR__ROWGU__19DFD96B]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  CONSTRAINT [DEFAULT_SA_ROLE_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  CONSTRAINT [DEFAULT_SA_ROLE_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DF__SA_USERS__ROWGUI__1DB06A4F]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DF__SA_USERS__IS_ACT__1EA48E88]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DF__SA_USERS__REMARK__2C88998B]  DEFAULT (NULL) FOR [REMARK]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DEFAULT_SA_USER_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[SA_USER] ADD  CONSTRAINT [DEFAULT_SA_USER_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[TRF_CODES] ADD  CONSTRAINT [DF__TRF_CODES__ROWGU__3C34F16F]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[TRF_CODES] ADD  CONSTRAINT [DEFAULT_TRF_CODES_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[TRF_CODES] ADD  CONSTRAINT [DEFAULT_TRF_CODES_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  CONSTRAINT [DF__TRF_STD__ROWGUID__531856C7]  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  CONSTRAINT [DEFAULT_TRF_STD_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  CONSTRAINT [DEFAULT_TRF_STD_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER DATABASE [SFCM] SET  READ_WRITE 
GO

INSERT INTO SA_ROLE (ROLE_CODE, ROLE_NAME,CREATE_BY,UPDATE_BY)
VALUES ('admin','Admin','sql','sql'),
('manager','Manager','sql','sql')

INSERT INTO SA_MENU (PARENT_CODE,MENU_CODE,MENU_NAME,MENU_ICON,IS_VISIBLE,ORDER_BY,VIEW_PAGE,CREATE_BY,UPDATE_BY)
VALUES 
(NULL,'user-manager',N'Quản lý người dùng','Users',1,100,NULL,'sql','sql'),
('user-manager','user',N'Người dùng',NULL,1,101,'User','sql','sql'),
('user-manager','permission',N'Phân quyền',NULL,1,102,'Permission','sql','sql'),
(NULL,'danhmucdungchung',N'Danh mục dùng chung','List',1,200,'DanhMucDungChung','sql','sql'),
('danhmucdungchung','thietkekho',N'Thiết kế kho',NULL,1,201,'ThietKeKho','sql','sql'),
('danhmucdungchung','quanlykho',N'Quản lý kho',NULL,1,202,'QuanLyKho','sql','sql')

INSERT INTO SA_PERMISSION (ROLE_CODE,MENU_CODE,IS_VIEW,IS_ADD_NEW,IS_MODIFY,IS_DELETE,CREATE_BY,UPDATE_BY)
VALUES 
('admin','user',1,1,1,1,'sql','sql'),
('admin','permission',1,1,1,1,'sql','sql'),
('admin','thietkekho',1,1,1,1,'sql','sql'),
('admin','quanlykho',1,1,1,1,'sql','sql'),
('manager','user',1,1,1,1,'sql','sql'),
('manager','permission',1,0,0,0,'sql','sql'),
('manager','thietkekho',1,1,1,1,'sql','sql'),
('manager','quanlykho',1,1,1,1,'sql','sql')

INSERT INTO SA_USER (ROLE_CODE, USER_NAME,CREATE_BY,UPDATE_BY)
VALUES ('admin','superadmin','sql','sql')

