USE MASTER
GO
-- Kiểm tra xem cơ sở dữ liệu 'SFCM' đã tồn tại chưa
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'SFCM')
BEGIN
    -- Nếu tồn tại, thì xóa cơ sở dữ liệu 'SFCM'
    DROP DATABASE SFCM
END
-- Tạo mới cơ sở dữ liệu 'SFCM'
GO
CREATE DATABASE SFCM

-- Sử dụng cơ sở dữ liệu 'SFCM' để tạo các bảng
GO
USE SFCM
GO

USE [SFCM]
GO
/****** Object:  Table [dbo].[BS_BLOCK]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_BLOCK](
	[BLOCK_CODE] [nvarchar](10) NOT NULL,
	[BLOCK_NAME] [nvarchar](250) NOT NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NOT NULL,
	[TIER_COUNT] [int] NULL,
	[SLOT_COUNT] [int] NULL,
	[BLOCK_LENGTH] [numeric](10, 2) NOT NULL,
	[BLOCK_WIDTH] [numeric](10, 2) NOT NULL,
	[BLOCK_HEIGHT] [numeric](10, 2) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BLOCK_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_CELL]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_CELL](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NOT NULL,
	[BLOCK_CODE] [nvarchar](10) NOT NULL,
	[TIER_ORDERED] [int] NULL,
	[SLOT_ORDERED] [int] NULL,
	[STATUS] [int] NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[CELL_LENGTH] [numeric](10, 2) NOT NULL,
	[CELL_WIDTH] [numeric](10, 2) NOT NULL,
	[CELL_HEIGHT] [numeric](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_CUSTOMER]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_CUSTOMER](
	[CUSTOMER_TYPE_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_NAME] [nvarchar](500) NOT NULL,
	[ADDRESS] [nvarchar](max) NULL,
	[TAX_CODE] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](200) NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_CUSTOMER_TYPE]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_CUSTOMER_TYPE](
	[CUSTOMER_TYPE_CODE] [nvarchar](50) NOT NULL,
	[CUSTOMER_TYPE_NAME] [nvarchar](500) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_EQUIPMENTS]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_EQUIPMENTS](
	[EQU_CODE] [nvarchar](10) NOT NULL,
	[EQU_TYPE] [nvarchar](10) NOT NULL,
	[EQU_CODE_NAME] [nvarchar](50) NOT NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EQU_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_EQUIPMENTS_TYPE]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_EQUIPMENTS_TYPE](
	[EQU_TYPE] [nvarchar](10) NOT NULL,
	[EQU_TYPE_NAME] [nvarchar](50) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EQU_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_GATE]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_GATE](
	[GATE_CODE] [nvarchar](50) NOT NULL,
	[GATE_NAME] [nvarchar](500) NOT NULL,
	[IS_IN_OUT] [char](1) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GATE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_ITEM_TYPE]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_ITEM_TYPE](
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[ITEM_TYPE_NAME] [nvarchar](500) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ITEM_TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_METHOD]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_METHOD](
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[METHOD_NAME] [nvarchar](500) NOT NULL,
	[IS_IN_OUT] [char](1) NOT NULL,
	[IS_SERVICE] [bit] NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[METHOD_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_TRUCK]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_TRUCK](
	[TRUCK_NO] [nvarchar](50) NOT NULL,
	[WEIGHT_REGIS] [numeric](18, 2) NULL,
	[WEIGHT_REGIS_ALLOW] [numeric](18, 2) NULL,
	[TRUCK_DATE_EXP] [datetime] NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRUCK_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_UNIT]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_UNIT](
	[UNIT_CODE] [nvarchar](50) NOT NULL,
	[UNIT_NAME] [nvarchar](500) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UNIT_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BS_WAREHOUSE]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BS_WAREHOUSE](
	[WAREHOUSE_CODE] [nvarchar](50) NOT NULL,
	[WAREHOUSE_NAME] [nvarchar](500) NOT NULL,
	[ACREAGE] [numeric](18, 3) NOT NULL,
	[STATUS] [bit] NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WAREHOUSE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_CNTR_MNF_LD]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_CNTR_MNF_LD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[SEALNO] [nvarchar](35) NULL,
	[CNTRNO] [varchar](11) NOT NULL,
	[CNTRSZTP] [varchar](5) NOT NULL,
	[STATUSOFGOOD] [bit] NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
	[CONSIGNEE] [nvarchar](50) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_ORDER]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_ORDER](
	[ORDER_NO] [nvarchar](50) NOT NULL,
	[CUSTOMER_CODE] [nvarchar](50) NOT NULL,
	[BILLOFLADING] [varchar](50) NULL,
	[REF_CONTAINER] [uniqueidentifier] NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NULL,
	[ITEM_TYPE_CODE_CNTR] [nvarchar](50) NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[ISSUE_DATE] [datetime] NOT NULL,
	[EXP_DATE] [datetime] NOT NULL,
	[TOTAL_CBM] [decimal](10, 3) NULL,
	[NOTE] [nvarchar](max) NULL,
	[DRAFT_NO] [nvarchar](20) NULL,
	[INV_NO] [nvarchar](20) NULL,
	[GATE_CHK] [bit] NOT NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ORDER_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_ORDER_DTLS]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_ORDER_DTLS](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ORDER_NO] [nvarchar](50) NOT NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[CBM] [decimal](10, 3) NULL,
	[LOT_NO] [int] NULL,
	[QUANTITY_CHK] [bit] NOT NULL,
	[REF_PAKAGE] [uniqueidentifier] NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_PACKAGE_MNF_LD]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_PACKAGE_MNF_LD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[HOUSE_BILL] [nvarchar](200) NOT NULL,
	[LOT_NO] [nvarchar](10) NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[UNIT_CODE] [nvarchar](50) NOT NULL,
	[CARGO_PIECE] [int] NULL,
	[CBM] [decimal](10, 3) NOT NULL,
	[DECLARE_NO] [varchar](max) NOT NULL,
	[NOTE] [nvarchar](max) NULL,
	[REF_CONTAINER] [uniqueidentifier] NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_PACKAGE_STOCK]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_PACKAGE_STOCK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NULL,
	[ORDER_NO] [nvarchar](50) NULL,
	[CUSTOMER_CODE] [nvarchar](50) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[CNTRNO] [varchar](11) NULL,
	[STATUS] [char](1) NULL,
	[TIME_IN] [datetime] NULL,
	[TIME_OUT] [datetime] NULL,
	[CARGO_PIECE] [int] NULL,
	[UNIT_CODE] [nvarchar](50) NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NULL,
	[CBM] [decimal](10, 3) NULL,
	[TLHQ] [bit] NULL,
	[METHOD_IN] [nvarchar](50) NULL,
	[METHOD_OUT] [nvarchar](50) NULL,
	[NOTE] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[COMMODITYDESCRIPTION] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_PALLET_STOCK]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_PALLET_STOCK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[REF_STOCK] [uniqueidentifier] NULL,
	[HOUSE_BILL] [varchar](50) NULL,
	[PALLET_NO] [nvarchar](100) NULL,
	[CARGO_PIECE] [int] NULL,
	[UNIT_CODE] [nvarchar](50) NULL,
	[WAREHOUSE_CODE] [varchar](50) NULL,
	[BLOCK] [nvarchar](5) NULL,
	[SLOT] [int] NULL,
	[TIER] [int] NULL,
	[STATUS] [char](1) NULL,
	[NOTE] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DT_VESSEL_VISIT]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DT_VESSEL_VISIT](
	[VOYAGEKEY] [nvarchar](50) NOT NULL,
	[VESSEL_NAME] [nvarchar](200) NOT NULL,
	[INBOUND_VOYAGE] [varchar](20) NOT NULL,
	[ETA] [datetime] NOT NULL,
	[CallSign] [varchar](50) NULL,
	[IMO] [varchar](30) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[VOYAGEKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_DFT]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_DFT](
	[DRAFT_INV_NO] [nvarchar](20) NOT NULL,
	[INV_NO] [nvarchar](20) NULL,
	[DRAFT_INV_DATE] [datetime] NULL,
	[PAYER_TYPE] [nvarchar](3) NULL,
	[PAYER] [nvarchar](20) NULL,
	[AMOUNT] [numeric](12, 2) NULL,
	[VAT] [numeric](12, 2) NULL,
	[REMARK] [nvarchar](100) NULL,
	[PAYMENT_STATUS] [nvarchar](1) NULL,
	[CURRENCYID] [nvarchar](3) NULL,
	[RATE] [numeric](14, 2) NULL,
	[INV_TYPE] [nvarchar](3) NULL,
	[TAMOUNT] [numeric](12, 2) NULL,
	[CREATE_BY] [nvarchar](50) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DRAFT_INV_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_DFT_DTL]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_DFT_DTL](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[DRAFT_INV_NO] [nvarchar](20) NOT NULL,
	[SEQ] [int] NOT NULL,
	[TRF_CODE] [nvarchar](12) NULL,
	[CARGO_TYPE] [nvarchar](2) NULL,
	[QTY] [numeric](12, 2) NULL,
	[UNIT_RATE] [numeric](15, 5) NULL,
	[AMOUNT] [numeric](12, 2) NULL,
	[VAT_RATE] [numeric](5, 2) NULL,
	[VAT] [numeric](12, 2) NULL,
	[TAMOUNT] [numeric](12, 2) NULL,
	[TRF_DESC] [nvarchar](500) NULL,
	[INV_UNIT] [nvarchar](3) NULL,
	[VAT_CHK] [bit] NULL,
	[REMARK] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INV_VAT]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INV_VAT](
	[INV_NO] [nvarchar](20) NOT NULL,
	[ORDER_NO] [nvarchar](50) NOT NULL,
	[INV_DATE] [datetime] NULL,
	[PAYER_TYPE] [nvarchar](3) NULL,
	[PAYER] [nvarchar](20) NULL,
	[AMOUNT] [numeric](12, 2) NULL,
	[VAT] [numeric](12, 2) NULL,
	[REMARK] [nvarchar](100) NULL,
	[PAYMENT_STATUS] [nvarchar](1) NULL,
	[CURRENCYID] [nvarchar](3) NULL,
	[RATE] [numeric](14, 2) NULL,
	[INV_TYPE] [nvarchar](3) NULL,
	[TAMOUNT] [numeric](12, 2) NULL,
	[ACC_CD] [nvarchar](10) NULL,
	[CANCEL_DATE] [datetime] NULL,
	[CANCLE_REMARK] [nvarchar](200) NULL,
	[CANCLE_BY] [nvarchar](25) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[INV_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_GATE]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_GATE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ORDER_NO] [nvarchar](50) NOT NULL,
	[WAREHOUSE_CODE] [nvarchar](50) NOT NULL,
	[GATE_CODE] [nvarchar](50) NOT NULL,
	[IS_IN_OUT] [char](1) NOT NULL,
	[DRIVER] [nvarchar](500) NULL,
	[TEL] [nvarchar](20) NULL,
	[TRUCK_NO] [nvarchar](50) NULL,
	[WEIGHT_REGIS] [numeric](18, 2) NULL,
	[WEIGHT_REGIS_ALLOW] [numeric](18, 2) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[CARGO_PIECE] [int] NULL,
	[UNIT_CODE] [nvarchar](50) NULL,
	[NOTE] [nvarchar](max) NULL,
	[TIME_IN] [datetime] NULL,
	[TIME_OUT] [datetime] NULL,
	[IS_SUCCESS_IN] [bit] NULL,
	[IS_SUCCESS_OUT] [bit] NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_QUANTITY_CHECK]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_QUANTITY_CHECK](
	[PALLET_NO] [nvarchar](100) NOT NULL,
	[VOYAGEKEY] [nvarchar](50) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[ESTIMATED_CARGO_PIECE] [int] NULL,
	[ACTUAL_CARGO_PIECE] [int] NULL,
	[ACTUAL_UNIT] [nvarchar](50) NULL,
	[SEQ] [int] NULL,
	[START_DATE] [datetime] NULL,
	[FINISH_DATE] [datetime] NULL,
	[IS_FINAL] [bit] NULL,
	[JOB_STATUS] [char](1) NULL,
	[NOTE] [nvarchar](max) NULL,
	[REF_GATE] [uniqueidentifier] NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PALLET_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[JOB_STOCK]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB_STOCK](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[JOB_TYPE] [nvarchar](10) NULL,
	[HOUSE_BILL] [nvarchar](200) NULL,
	[ORDER_NO] [nvarchar](50) NULL,
	[PALLET_NO] [nvarchar](100) NULL,
	[SEQ] [int] NULL,
	[ACTUAL_CARGO_PIECE] [int] NULL,
	[ACTUAL_UNIT] [nvarchar](50) NULL,
	[BLOCK] [nvarchar](5) NULL,
	[SLOT] [int] NULL,
	[TIER] [int] NULL,
	[JOB_STATUS] [char](1) NULL,
	[REF_CELL] [uniqueidentifier] NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_MENU]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_MENU](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[PARENT_CODE] [nvarchar](255) NULL,
	[MENU_CODE] [nvarchar](100) NOT NULL,
	[MENU_NAME] [nvarchar](max) NOT NULL,
	[MENU_ICON] [nvarchar](255) NULL,
	[IS_VISIBLE] [bit] NOT NULL,
	[ORDER_BY] [int] NOT NULL,
	[VIEW_PAGE] [nvarchar](100) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_PERMISSION]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_PERMISSION](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ROLE_CODE] [nvarchar](100) NOT NULL,
	[MENU_CODE] [nvarchar](500) NOT NULL,
	[IS_VIEW] [bit] NULL,
	[IS_ADD_NEW] [bit] NULL,
	[IS_MODIFY] [bit] NULL,
	[IS_DELETE] [bit] NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_ROLE]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_ROLE](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[ROLE_CODE] [nvarchar](50) NOT NULL,
	[ROLE_NAME] [nvarchar](500) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SA_USER]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SA_USER](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[USER_NAME] [nvarchar](max) NOT NULL,
	[PASSWORD] [nvarchar](100) NULL,
	[ROLE_CODE] [nvarchar](100) NOT NULL,
	[FULLNAME] [nvarchar](50) NULL,
	[BIRTHDAY] [datetime] NULL,
	[ADDRESS] [nvarchar](500) NULL,
	[TELEPHONE] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](max) NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[REMARK] [nvarchar](max) NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_CODES]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_CODES](
	[TRF_CODE] [nvarchar](12) NOT NULL,
	[TRF_DESC] [nvarchar](150) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRF_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_STD]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_STD](
	[ROWGUID] [uniqueidentifier] NOT NULL,
	[TRF_CODE] [nvarchar](12) NOT NULL,
	[TRF_DESC] [nvarchar](150) NULL,
	[METHOD_CODE] [nvarchar](50) NOT NULL,
	[ITEM_TYPE_CODE] [nvarchar](50) NOT NULL,
	[AMT_CBM] [numeric](12, 2) NOT NULL,
	[VAT] [numeric](5, 2) NULL,
	[INCLUDE_VAT] [bit] NULL,
	[TRF_TEMP_CODE] [nvarchar](100) NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](500) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ROWGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRF_TEMP]    Script Date: 7/2/2024 9:41:41 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRF_TEMP](
	[TRF_TEMP_CODE] [nvarchar](100) NOT NULL,
	[TRF_TEMP_NAME] [nvarchar](50) NOT NULL,
	[FROM_DATE] [datetime] NOT NULL,
	[TO_DATE] [datetime] NOT NULL,
	[CREATE_BY] [nvarchar](100) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](100) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.TRF_TEMP] PRIMARY KEY CLUSTERED 
(
	[TRF_TEMP_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BS_BLOCK] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_BLOCK] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_CELL] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[BS_CELL] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_CELL] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  CONSTRAINT [DEFAULT_BS_CUSTOMER_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER_TYPE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_CUSTOMER_TYPE] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS_TYPE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS_TYPE] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_GATE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_GATE] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_ITEM_TYPE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_ITEM_TYPE] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_METHOD] ADD  CONSTRAINT [DEFAULT_BS_METHOD_IS_SERVICE]  DEFAULT ((0)) FOR [IS_SERVICE]
GO
ALTER TABLE [dbo].[BS_METHOD] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_METHOD] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_TRUCK] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_TRUCK] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_UNIT] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_UNIT] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_WAREHOUSE] ADD  DEFAULT ((0)) FOR [STATUS]
GO
ALTER TABLE [dbo].[BS_WAREHOUSE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[BS_WAREHOUSE] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  CONSTRAINT [DEFAULT_DT_CNTR_MNF_LD_STATUSOFGOOD]  DEFAULT ((1)) FOR [STATUSOFGOOD]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[DT_ORDER] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_ORDER] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[DT_ORDER_DTLS] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[DT_VESSEL_VISIT] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[DT_VESSEL_VISIT] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[INV_DFT] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[INV_DFT] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[INV_DFT_DTL] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[INV_DFT_DTL] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[INV_DFT_DTL] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[INV_VAT] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[INV_VAT] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[JOB_GATE] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[JOB_STOCK] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[JOB_STOCK] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[JOB_STOCK] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[SA_MENU] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[SA_PERMISSION] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[SA_ROLE] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[SA_USER] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[SA_USER] ADD  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[SA_USER] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[SA_USER] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[TRF_CODES] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[TRF_CODES] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  DEFAULT (newid()) FOR [ROWGUID]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
ALTER TABLE [dbo].[TRF_STD] ADD  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
ALTER TABLE [dbo].[BS_BLOCK]  WITH CHECK ADD  CONSTRAINT [FK_BS_BLOCK_WAREHOUSE] FOREIGN KEY([WAREHOUSE_CODE])
REFERENCES [dbo].[BS_WAREHOUSE] ([WAREHOUSE_CODE])
GO
ALTER TABLE [dbo].[BS_BLOCK] CHECK CONSTRAINT [FK_BS_BLOCK_WAREHOUSE]
GO
ALTER TABLE [dbo].[BS_CELL]  WITH CHECK ADD  CONSTRAINT [FK_BS_CELL_BLOCK] FOREIGN KEY([BLOCK_CODE])
REFERENCES [dbo].[BS_BLOCK] ([BLOCK_CODE])
GO
ALTER TABLE [dbo].[BS_CELL] CHECK CONSTRAINT [FK_BS_CELL_BLOCK]
GO
ALTER TABLE [dbo].[BS_CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_BS_CUSTOMER_CUSTOMER_TYPE] FOREIGN KEY([CUSTOMER_TYPE_CODE])
REFERENCES [dbo].[BS_CUSTOMER_TYPE] ([CUSTOMER_TYPE_CODE])
GO
ALTER TABLE [dbo].[BS_CUSTOMER] CHECK CONSTRAINT [FK_BS_CUSTOMER_CUSTOMER_TYPE]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS]  WITH NOCHECK ADD  CONSTRAINT [FK_BS_EQUIPMENTS_BS_WAREHOUSE] FOREIGN KEY([WAREHOUSE_CODE])
REFERENCES [dbo].[BS_WAREHOUSE] ([WAREHOUSE_CODE])
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS] CHECK CONSTRAINT [FK_BS_EQUIPMENTS_BS_WAREHOUSE]
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS]  WITH CHECK ADD  CONSTRAINT [FK_BS_EQUIPMENTS_TYPE] FOREIGN KEY([EQU_TYPE])
REFERENCES [dbo].[BS_EQUIPMENTS_TYPE] ([EQU_TYPE])
GO
ALTER TABLE [dbo].[BS_EQUIPMENTS] CHECK CONSTRAINT [FK_BS_EQUIPMENTS_TYPE]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD]  WITH CHECK ADD  CONSTRAINT [FK_DT_CNTR_MNF_LD_BS_CUSTOMER] FOREIGN KEY([CONSIGNEE])
REFERENCES [dbo].[BS_CUSTOMER] ([CUSTOMER_CODE])
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] CHECK CONSTRAINT [FK_DT_CNTR_MNF_LD_BS_CUSTOMER]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD]  WITH CHECK ADD  CONSTRAINT [FK_DT_CNTR_MNF_LD_ITEM_TYPE] FOREIGN KEY([ITEM_TYPE_CODE])
REFERENCES [dbo].[BS_ITEM_TYPE] ([ITEM_TYPE_CODE])
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] CHECK CONSTRAINT [FK_DT_CNTR_MNF_LD_ITEM_TYPE]
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD]  WITH CHECK ADD  CONSTRAINT [FK_DT_CNTR_MNF_LD_VESSEL_VISIT] FOREIGN KEY([VOYAGEKEY])
REFERENCES [dbo].[DT_VESSEL_VISIT] ([VOYAGEKEY])
GO
ALTER TABLE [dbo].[DT_CNTR_MNF_LD] CHECK CONSTRAINT [FK_DT_CNTR_MNF_LD_VESSEL_VISIT]
GO
ALTER TABLE [dbo].[DT_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_DT_ORDER_CONTAINER] FOREIGN KEY([REF_CONTAINER])
REFERENCES [dbo].[DT_CNTR_MNF_LD] ([ROWGUID])
GO
ALTER TABLE [dbo].[DT_ORDER] CHECK CONSTRAINT [FK_DT_ORDER_CONTAINER]
GO
ALTER TABLE [dbo].[DT_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_DT_ORDER_CUSTOMER] FOREIGN KEY([CUSTOMER_CODE])
REFERENCES [dbo].[BS_CUSTOMER] ([CUSTOMER_CODE])
GO
ALTER TABLE [dbo].[DT_ORDER] CHECK CONSTRAINT [FK_DT_ORDER_CUSTOMER]
GO
ALTER TABLE [dbo].[DT_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_DT_ORDER_DRAFT_NO] FOREIGN KEY([DRAFT_NO])
REFERENCES [dbo].[INV_DFT] ([DRAFT_INV_NO])
GO
ALTER TABLE [dbo].[DT_ORDER] CHECK CONSTRAINT [FK_DT_ORDER_DRAFT_NO]
GO
ALTER TABLE [dbo].[DT_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_DT_ORDER_INV_NO] FOREIGN KEY([INV_NO])
REFERENCES [dbo].[INV_VAT] ([INV_NO])
GO
ALTER TABLE [dbo].[DT_ORDER] CHECK CONSTRAINT [FK_DT_ORDER_INV_NO]
GO
ALTER TABLE [dbo].[DT_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_DT_ORDER_METHOD] FOREIGN KEY([METHOD_CODE])
REFERENCES [dbo].[BS_METHOD] ([METHOD_CODE])
GO
ALTER TABLE [dbo].[DT_ORDER] CHECK CONSTRAINT [FK_DT_ORDER_METHOD]
GO
ALTER TABLE [dbo].[DT_ORDER_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_DT_ORDER_DTLS_ORDER] FOREIGN KEY([ORDER_NO])
REFERENCES [dbo].[DT_ORDER] ([ORDER_NO])
GO
ALTER TABLE [dbo].[DT_ORDER_DTLS] CHECK CONSTRAINT [FK_DT_ORDER_DTLS_ORDER]
GO
ALTER TABLE [dbo].[DT_ORDER_DTLS]  WITH CHECK ADD  CONSTRAINT [FK_DT_ORDER_DTLS_PACKAGE] FOREIGN KEY([REF_PAKAGE])
REFERENCES [dbo].[DT_PACKAGE_MNF_LD] ([ROWGUID])
GO
ALTER TABLE [dbo].[DT_ORDER_DTLS] CHECK CONSTRAINT [FK_DT_ORDER_DTLS_PACKAGE]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD]  WITH CHECK ADD  CONSTRAINT [FK_DT_PACKAGE_MNF_LD_CONTAINER] FOREIGN KEY([REF_CONTAINER])
REFERENCES [dbo].[DT_CNTR_MNF_LD] ([ROWGUID])
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] CHECK CONSTRAINT [FK_DT_PACKAGE_MNF_LD_CONTAINER]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD]  WITH CHECK ADD  CONSTRAINT [FK_DT_PACKAGE_MNF_LD_ITEM_TYPE] FOREIGN KEY([ITEM_TYPE_CODE])
REFERENCES [dbo].[BS_ITEM_TYPE] ([ITEM_TYPE_CODE])
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] CHECK CONSTRAINT [FK_DT_PACKAGE_MNF_LD_ITEM_TYPE]
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD]  WITH CHECK ADD  CONSTRAINT [FK_DT_PACKAGE_MNF_LD_UNIT] FOREIGN KEY([UNIT_CODE])
REFERENCES [dbo].[BS_UNIT] ([UNIT_CODE])
GO
ALTER TABLE [dbo].[DT_PACKAGE_MNF_LD] CHECK CONSTRAINT [FK_DT_PACKAGE_MNF_LD_UNIT]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_DT_PACKAGE_STOCK_ORDER] FOREIGN KEY([ORDER_NO])
REFERENCES [dbo].[DT_ORDER] ([ORDER_NO])
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] CHECK CONSTRAINT [FK_DT_PACKAGE_STOCK_ORDER]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_DT_PACKAGE_STOCK_VESSEL_VISIT] FOREIGN KEY([VOYAGEKEY])
REFERENCES [dbo].[DT_VESSEL_VISIT] ([VOYAGEKEY])
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] CHECK CONSTRAINT [FK_DT_PACKAGE_STOCK_VESSEL_VISIT]
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_DT_PACKAGE_STOCK_WAREHOUSE] FOREIGN KEY([WAREHOUSE_CODE])
REFERENCES [dbo].[BS_WAREHOUSE] ([WAREHOUSE_CODE])
GO
ALTER TABLE [dbo].[DT_PACKAGE_STOCK] CHECK CONSTRAINT [FK_DT_PACKAGE_STOCK_WAREHOUSE]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_DT_PALLET_STOCK_PALLET] FOREIGN KEY([PALLET_NO])
REFERENCES [dbo].[JOB_QUANTITY_CHECK] ([PALLET_NO])
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] CHECK CONSTRAINT [FK_DT_PALLET_STOCK_PALLET]
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_DT_PALLET_STOCK_STOCK] FOREIGN KEY([REF_STOCK])
REFERENCES [dbo].[DT_PACKAGE_STOCK] ([ROWGUID])
GO
ALTER TABLE [dbo].[DT_PALLET_STOCK] CHECK CONSTRAINT [FK_DT_PALLET_STOCK_STOCK]
GO
ALTER TABLE [dbo].[INV_DFT]  WITH CHECK ADD  CONSTRAINT [FK_INV_DFT_INV_VAT] FOREIGN KEY([INV_NO])
REFERENCES [dbo].[INV_VAT] ([INV_NO])
GO
ALTER TABLE [dbo].[INV_DFT] CHECK CONSTRAINT [FK_INV_DFT_INV_VAT]
GO
ALTER TABLE [dbo].[INV_DFT_DTL]  WITH CHECK ADD  CONSTRAINT [FK_INV_DFT_DTL_DRAFT_INV] FOREIGN KEY([DRAFT_INV_NO])
REFERENCES [dbo].[INV_DFT] ([DRAFT_INV_NO])
GO
ALTER TABLE [dbo].[INV_DFT_DTL] CHECK CONSTRAINT [FK_INV_DFT_DTL_DRAFT_INV]
GO
ALTER TABLE [dbo].[INV_VAT]  WITH NOCHECK ADD  CONSTRAINT [FK_INV_VAT_DT_ORDER] FOREIGN KEY([ORDER_NO])
REFERENCES [dbo].[DT_ORDER] ([ORDER_NO])
GO
ALTER TABLE [dbo].[INV_VAT] CHECK CONSTRAINT [FK_INV_VAT_DT_ORDER]
GO
ALTER TABLE [dbo].[JOB_GATE]  WITH CHECK ADD  CONSTRAINT [FK_JOB_GATE_BS_UNIT] FOREIGN KEY([UNIT_CODE])
REFERENCES [dbo].[BS_UNIT] ([UNIT_CODE])
GO
ALTER TABLE [dbo].[JOB_GATE] CHECK CONSTRAINT [FK_JOB_GATE_BS_UNIT]
GO
ALTER TABLE [dbo].[JOB_GATE]  WITH CHECK ADD  CONSTRAINT [FK_JOB_GATE_GATE] FOREIGN KEY([GATE_CODE])
REFERENCES [dbo].[BS_GATE] ([GATE_CODE])
GO
ALTER TABLE [dbo].[JOB_GATE] CHECK CONSTRAINT [FK_JOB_GATE_GATE]
GO
ALTER TABLE [dbo].[JOB_GATE]  WITH CHECK ADD  CONSTRAINT [FK_JOB_GATE_ORDER] FOREIGN KEY([ORDER_NO])
REFERENCES [dbo].[DT_ORDER] ([ORDER_NO])
GO
ALTER TABLE [dbo].[JOB_GATE] CHECK CONSTRAINT [FK_JOB_GATE_ORDER]
GO
ALTER TABLE [dbo].[JOB_GATE]  WITH CHECK ADD  CONSTRAINT [FK_JOB_GATE_WAREHOUSE] FOREIGN KEY([WAREHOUSE_CODE])
REFERENCES [dbo].[BS_WAREHOUSE] ([WAREHOUSE_CODE])
GO
ALTER TABLE [dbo].[JOB_GATE] CHECK CONSTRAINT [FK_JOB_GATE_WAREHOUSE]
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK]  WITH CHECK ADD  CONSTRAINT [FK_JOB_QUANTITY_CHECK_GATE] FOREIGN KEY([REF_GATE])
REFERENCES [dbo].[JOB_GATE] ([ROWGUID])
GO
ALTER TABLE [dbo].[JOB_QUANTITY_CHECK] CHECK CONSTRAINT [FK_JOB_QUANTITY_CHECK_GATE]
GO
ALTER TABLE [dbo].[JOB_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_JOB_STOCK_CELL] FOREIGN KEY([REF_CELL])
REFERENCES [dbo].[BS_CELL] ([ROWGUID])
GO
ALTER TABLE [dbo].[JOB_STOCK] CHECK CONSTRAINT [FK_JOB_STOCK_CELL]
GO
ALTER TABLE [dbo].[JOB_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_JOB_STOCK_ORDER] FOREIGN KEY([ORDER_NO])
REFERENCES [dbo].[DT_ORDER] ([ORDER_NO])
GO
ALTER TABLE [dbo].[JOB_STOCK] CHECK CONSTRAINT [FK_JOB_STOCK_ORDER]
GO
ALTER TABLE [dbo].[JOB_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_JOB_STOCK_PALLET] FOREIGN KEY([PALLET_NO])
REFERENCES [dbo].[JOB_QUANTITY_CHECK] ([PALLET_NO])
GO
ALTER TABLE [dbo].[JOB_STOCK] CHECK CONSTRAINT [FK_JOB_STOCK_PALLET]
GO
ALTER TABLE [dbo].[TRF_STD]  WITH CHECK ADD  CONSTRAINT [FK_TRF_STD_ITEM_TYPE] FOREIGN KEY([ITEM_TYPE_CODE])
REFERENCES [dbo].[BS_ITEM_TYPE] ([ITEM_TYPE_CODE])
GO
ALTER TABLE [dbo].[TRF_STD] CHECK CONSTRAINT [FK_TRF_STD_ITEM_TYPE]
GO
ALTER TABLE [dbo].[TRF_STD]  WITH CHECK ADD  CONSTRAINT [FK_TRF_STD_METHOD] FOREIGN KEY([METHOD_CODE])
REFERENCES [dbo].[BS_METHOD] ([METHOD_CODE])
GO
ALTER TABLE [dbo].[TRF_STD] CHECK CONSTRAINT [FK_TRF_STD_METHOD]
GO
ALTER TABLE [dbo].[TRF_STD]  WITH CHECK ADD  CONSTRAINT [FK_TRF_STD_TRF_CODES] FOREIGN KEY([TRF_CODE])
REFERENCES [dbo].[TRF_CODES] ([TRF_CODE])
GO
ALTER TABLE [dbo].[TRF_STD] CHECK CONSTRAINT [FK_TRF_STD_TRF_CODES]
GO
ALTER TABLE [dbo].[TRF_STD]  WITH CHECK ADD  CONSTRAINT [FK_TRF_STD_TRF_TEMP] FOREIGN KEY([TRF_TEMP_CODE])
REFERENCES [dbo].[TRF_TEMP] ([TRF_TEMP_CODE])
GO
ALTER TABLE [dbo].[TRF_STD] CHECK CONSTRAINT [FK_TRF_STD_TRF_TEMP]
GO
